In [1]:
import pandas as pd
import numpy as np

In [ ]:
wnba_raw = pd.read_csv("data/wnba_raw.csv")
wbb_raw = pd.read_csv("data/wbb_raw.csv")

In [3]:
wnba_raw.head(10)

,game_play_number,id,sequence_number,type_id,type_text,text,away_score,home_score,period_number,period_display_value,...,end_half_seconds_remaining,end_game_seconds_remaining,period,lag_qtr,lag_half,coordinate_x,coordinate_y,game_date,game_date_time,type_abbreviation
0,1,4018570064,4,615,Jumpball,Aliyah Boston vs. Angel Reese,0,0,1,1st Quarter,...,1200.0,2400.0,1,NaN,NaN,2.147484e+08,214748365,2026-06-20,2026-06-20 13:00:00,NaN
1,2,4018570067,7,95,Layup Shot,Naz Hillmon misses layup,0,0,1,1st Quarter,...,1181.0,2381.0,1,1.0,1.0,3.975000e+01,2,2026-06-20,2026-06-20 13:00:00,NaN
2,3,4018570068,8,156,Offensive Rebound,Naz Hillmon offensive rebound,0,0,1,1st Quarter,...,1181.0,2381.0,1,1.0,1.0,3.975000e+01,2,2026-06-20,2026-06-20 13:00:00,NaN
3,4,4018570069,9,125,Layup Shot Putback,Naz Hillmon makes two point shot,0,2,1,1st Quarter,...,1181.0,2381.0,1,1.0,1.0,4.175000e+01,0,2026-06-20,2026-06-20 13:00:00,NaN
4,5,40185700610,10,44,Shooting Foul,Monique Billings shooting foul,0,2,1,1st Quarter,...,1181.0,2381.0,1,1.0,1.0,-4.175000e+01,0,2026-06-20,2026-06-20 13:00:00,NaN
5,6,40185700612,12,97,Free Throw - 1 of 1,Naz Hillmon makes free throw 1 of 1,0,3,1,1st Quarter,...,1166.0,2366.0,1,1.0,1.0,2.800000e+01,0,2026-06-20,2026-06-20 13:00:00,NaN
6,7,40185700613,13,141,Cutting Layup Shot,Kelsey Mitchell makes 1-foot layup (Aliyah Bos...,2,3,1,1st Quarter,...,1152.0,2352.0,1,1.0,1.0,-4.075000e+01,0,2026-06-20,2026-06-20 13:00:00,NaN
7,8,40185700615,15,92,Jump Shot,Naz Hillmon makes 24-foot three point jumper (...,2,6,1,1st Quarter,...,1130.0,2330.0,1,1.0,1.0,1.775000e+01,-1,2026-06-20,2026-06-20 13:00:00,NaN
8,9,40185700617,17,92,Jump Shot,Aliyah Boston makes 24-foot three point jumper...,5,6,1,1st Quarter,...,1118.0,2318.0,1,1.0,1.0,-1.775000e+01,-2,2026-06-20,2026-06-20 13:00:00,NaN
9,10,40185700619,19,64,Traveling,Angel Reese traveling turnover,5,6,1,1st Quarter,...,1108.0,2308.0,1,1.0,1.0,3.775000e+01,-3,2026-06-20,2026-06-20 13:00:00,NaN

In [4]:
wnba_raw.columns

Index(['game_play_number', 'id', 'sequence_number', 'type_id', 'type_text',
       'text', 'away_score', 'home_score', 'period_number',
       'period_display_value', 'clock_display_value', 'scoring_play',
       'score_value', 'team_id', 'athlete_id_1', 'athlete_id_2',
       'athlete_id_3', 'wallclock', 'shooting_play', 'coordinate_x_raw',
       'coordinate_y_raw', 'points_attempted', 'short_description', 'game_id',
       'season', 'season_type', 'home_team_id', 'home_team_name',
       'home_team_mascot', 'home_team_abbrev', 'home_team_name_alt',
       'away_team_id', 'away_team_name', 'away_team_mascot',
       'away_team_abbrev', 'away_team_name_alt', 'game_spread',
       'home_favorite', 'game_spread_available', 'home_team_spread', 'qtr',
       'time', 'clock_minutes', 'clock_seconds', 'home_timeout_called',
       'away_timeout_called', 'half', 'game_half', 'lead_qtr', 'lead_half',
       'start_quarter_seconds_remaining', 'start_half_seconds_remaining',
       'start_game_seconds_remaining', 'end_quarter_seconds_remaining',
       'end_half_seconds_remaining', 'end_game_seconds_remaining', 'period',
       'lag_qtr', 'lag_half', 'coordinate_x', 'coordinate_y', 'game_date',
       'game_date_time', 'type_abbreviation'],
      dtype='str')

In [5]:
print(wnba_raw['game_id'].unique())

[401857006 401857007 401857008 401857003 401857004 401857005 401857002
 401856996 401856997 401856998 401856999 401857000 401857001 401856995
 401856992 401856993 401856994 401856990 401856991 401856986 401856987
 401856988 401856989 401856984 401856985 401856980 401856981 401856982
 401856983 401856978 401856979 401856975 401856976 401856977 401856972
 401856973 401856974 401856970 401856971 401856966 401856967 401856968
 401856969 401856963 401856964 401856965 401856961 401856962 401856959
 401856960 401856955 401856956 401856957 401856958 401856953 401856954
 401856952 401856949 401856950 401856951 401856945 401856946 401856947
 401856948 401856943 401856944 401856938 401856939 401856940 401856941
 401856942 401856936 401856937 401856933 401856934 401856935 401856930
 401856931 401856932 401856927 401856928 401856929 401856924 401856925
 401856926 401856921 401856922 401856923 401856920 401856918 401856919
 401856915 401856916 401856914 401856917 401856910 401856911 401856912
 401856913 401856908 401856909 401856904 401856905 401856906 401856907
 401856901 401856902 401856903 401856896 401856897 401856898 401856900
 401856893 401856894 401856899 401856895 401856890 401856891 401856892]

In [14]:
game_by_game_dfs = {game_id: raw_data for game_id, raw_data in wnba_raw.groupby('game_id')}

,game_play_number,id,sequence_number,type_id,type_text,text,away_score,home_score,period_number,period_display_value,...,end_half_seconds_remaining,end_game_seconds_remaining,period,lag_qtr,lag_half,coordinate_x,coordinate_y,game_date,game_date_time,type_abbreviation
47125,1,4018568994,4,615,Jumpball,Angel Reese vs. Natasha Howard (Allisha Gray g...,0,0,1,1st Quarter,...,1200.0,2400.0,1,NaN,NaN,-2.147484e+08,-214748365,2026-05-09,2026-05-09 20:00:00,NaN
47126,2,4018568997,7,62,Bad Pass\nTurnover,Jordin Canada bad pass\nturnover (Natasha Howa...,0,0,1,1st Quarter,...,1182.0,2382.0,1,1.0,1.0,-2.750000e+00,4,2026-05-09,2026-05-09 20:00:00,NaN
47127,3,4018568999,9,113,Running Jump Shot,Nia Coffey makes 22-foot running jump shot (Ol...,0,3,1,1st Quarter,...,1157.0,2357.0,1,1.0,1.0,2.875000e+01,18,2026-05-09,2026-05-09 20:00:00,NaN
47128,4,40185689911,11,92,Jump Shot,Naz Hillmon misses 22-foot three point jumper,0,3,1,1st Quarter,...,1154.0,2354.0,1,1.0,1.0,-4.075000e+01,22,2026-05-09,2026-05-09 20:00:00,NaN
47129,5,40185689912,12,155,Defensive Rebound,Kayla McBride defensive rebound,0,3,1,1st Quarter,...,1149.0,2349.0,1,1.0,1.0,4.075000e+01,-22,2026-05-09,2026-05-09 20:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47581,457,401856899673,673,615,Jumpball,Naz Hillmon vs. Nia Coffey (Olivia Miles gains...,91,90,4,4th Quarter,...,0.0,0.0,4,4.0,2.0,2.147484e+08,214748365,2026-05-09,2026-05-09 20:00:00,NaN
47582,458,401856899676,676,95,Layup Shot,Angel Reese blocks Emese Hof 's 4-foot layup,91,90,4,4th Quarter,...,0.0,0.0,4,4.0,2.0,3.975000e+01,4,2026-05-09,2026-05-09 20:00:00,NaN
47583,459,401856899678,678,156,Offensive Rebound,Lynx offensive team rebound,91,90,4,4th Quarter,...,0.0,0.0,4,4.0,2.0,3.975000e+01,4,2026-05-09,2026-05-09 20:00:00,NaN
47584,460,401856899679,679,412,End Period,End of the 4th Quarter,91,90,4,4th Quarter,...,0.0,0.0,4,4.0,2.0,-2.147484e+08,-214748365,2026-05-09,2026-05-09 20:00:00,NaN
47585,461,401856899680,680,402,End Game,End of Game,91,90,4,4th Quarter,...,NaN,NaN,4,4.0,2.0,-2.147484e+08,-214748365,2026-05-09,2026-05-09 20:00:00,NaN

In [21]:
teams = pd.read_csv("data/wnba_teams.csv")
teams = teams.drop(columns = "fox_section")
teams = teams.rename(columns = {"fox_team_id": "team_id",
                      "fox_team_name": "team_name"})
teams.head(10)

   team_id               team_name
0        1           Atlanta Dream
1        5        New York Liberty
2        4           Indiana Fever
3        6      Washington Mystics
4       29           Toronto Tempo
5        2             Chicago Sky
6        3         Connecticut Sun
7        9          Minnesota Lynx
8       11          Las Vegas Aces
9       23  Golden State Valkyries

In [23]:
import os

roster_dfs = []

for roster_file in os.listdir("data/rosters"):
    roster_df = pd.read_csv(f"data/rosters/{roster_file}")
    roster_dfs.append(roster_df)

rosters = pd.concat(roster_dfs, ignore_index = True)
rosters.head(20)

,team_id,position_group,player,pos,age,ht,wt,college,athlete_id,Unnamed: 0
0,10.0,GUARD,Monique Akoa Makani,G,25.0,"5'10""",-,-,841.0,NaN
1,10.0,GUARD,DeWanna Bonner,G/F,38.0,"6'4""",140 lbs,Auburn,211.0,NaN
2,10.0,GUARD,Noemie Brochant,G/F,26.0,"5'11""",-,-,955.0,NaN
3,10.0,GUARD,Shay Ciezki,G,22.0,"5'7""",-,-,961.0,NaN
4,10.0,GUARD,Kahleah Copper,G/F,31.0,"6'1""",165 lbs,Rutgers,5.0,NaN
5,10.0,GUARD,Lexi Held,G,26.0,"5'9""",138 lbs,-,677.0,NaN
6,10.0,GUARD,Jovana Nogic,G,28.0,"6'0""",170 lbs,-,971.0,NaN
7,10.0,GUARD,Sami Whitcomb,G,37.0,"5'10""",149 lbs,Washington,167.0,NaN
8,10.0,FORWARD,Valeriane Ayayi,F,32.0,"6'1""",150 lbs,NaN,191.0,NaN
9,10.0,FORWARD,Quionche Carter,F,25.0,"5'11""",-,-,954.0,NaN
10,10.0,FORWARD,Natasha Mack,F/C,28.0,"6'3""",182 lbs,-,574.0,NaN
11,10.0,FORWARD,Marta Suarez,F,24.0,"6'3""",-,-,925.0,NaN
12,10.0,FORWARD,Alyssa Thomas,F,34.0,"6'2""",203 lbs,Maryland,110.0,NaN
13,10.0,CENTER,Kyara Linskens,C,29.0,"6'4""",209 lbs,-,832.0,NaN
14,2.0,GUARD,Rachel Banham,G,32.0,"5'10""",181 lbs,Minnesota,118.0,NaN
15,2.0,GUARD,DiJonai Carrington,G/F,28.0,"5'11""",175 lbs,-,585.0,NaN
16,2.0,GUARD,Natasha Cloud,G,34.0,"5'10""",160 lbs,St. Joseph's,170.0,NaN
17,2.0,GUARD,Aicha Coulibaly,G,24.0,"6'0""",-,-,858.0,NaN
18,2.0,GUARD,Skylar Diggins,G,35.0,"5'9""",140 lbs,Notre Dame,127.0,NaN
19,2.0,GUARD,Gabriela Jaquez,G,22.0,"6'0""",-,-,910.0,NaN

In [24]:
complete_player_list = pd.merge(rosters, teams, how = "left", on = "team_id")
complete_player_list.head(50)

,team_id,position_group,player,pos,age,ht,wt,college,athlete_id,Unnamed: 0,team_name
0,10.0,GUARD,Monique Akoa Makani,G,25.0,"5'10""",-,-,841.0,NaN,Phoenix Mercury
1,10.0,GUARD,DeWanna Bonner,G/F,38.0,"6'4""",140 lbs,Auburn,211.0,NaN,Phoenix Mercury
2,10.0,GUARD,Noemie Brochant,G/F,26.0,"5'11""",-,-,955.0,NaN,Phoenix Mercury
3,10.0,GUARD,Shay Ciezki,G,22.0,"5'7""",-,-,961.0,NaN,Phoenix Mercury
4,10.0,GUARD,Kahleah Copper,G/F,31.0,"6'1""",165 lbs,Rutgers,5.0,NaN,Phoenix Mercury
5,10.0,GUARD,Lexi Held,G,26.0,"5'9""",138 lbs,-,677.0,NaN,Phoenix Mercury
6,10.0,GUARD,Jovana Nogic,G,28.0,"6'0""",170 lbs,-,971.0,NaN,Phoenix Mercury
7,10.0,GUARD,Sami Whitcomb,G,37.0,"5'10""",149 lbs,Washington,167.0,NaN,Phoenix Mercury
8,10.0,FORWARD,Valeriane Ayayi,F,32.0,"6'1""",150 lbs,NaN,191.0,NaN,Phoenix Mercury
9,10.0,FORWARD,Quionche Carter,F,25.0,"5'11""",-,-,954.0,NaN,Phoenix Mercury
10,10.0,FORWARD,Natasha Mack,F/C,28.0,"6'3""",182 lbs,-,574.0,NaN,Phoenix Mercury
11,10.0,FORWARD,Marta Suarez,F,24.0,"6'3""",-,-,925.0,NaN,Phoenix Mercury
12,10.0,FORWARD,Alyssa Thomas,F,34.0,"6'2""",203 lbs,Maryland,110.0,NaN,Phoenix Mercury
13,10.0,CENTER,Kyara Linskens,C,29.0,"6'4""",209 lbs,-,832.0,NaN,Phoenix Mercury
14,2.0,GUARD,Rachel Banham,G,32.0,"5'10""",181 lbs,Minnesota,118.0,NaN,Chicago Sky
15,2.0,GUARD,DiJonai Carrington,G/F,28.0,"5'11""",175 lbs,-,585.0,NaN,Chicago Sky
16,2.0,GUARD,Natasha Cloud,G,34.0,"5'10""",160 lbs,St. Joseph's,170.0,NaN,Chicago Sky
17,2.0,GUARD,Aicha Coulibaly,G,24.0,"6'0""",-,-,858.0,NaN,Chicago Sky
18,2.0,GUARD,Skylar Diggins,G,35.0,"5'9""",140 lbs,Notre Dame,127.0,NaN,Chicago Sky
19,2.0,GUARD,Gabriela Jaquez,G,22.0,"6'0""",-,-,910.0,NaN,Chicago Sky
20,2.0,GUARD,Jacy Sheldon,G,25.0,"5'10""",140 lbs,-,709.0,NaN,Chicago Sky
21,2.0,GUARD,Sydney Taylor,G,25.0,"5'9""",-,-,953.0,NaN,Chicago Sky
22,2.0,GUARD,Courtney Vandersloot,G,37.0,"5'8""",137 lbs,Gonzaga,78.0,NaN,Chicago Sky
23,2.0,FORWARD,Rickea Jackson,F,25.0,"6'2""",175 lbs,-,717.0,NaN,Chicago Sky
24,2.0,FORWARD,Azurá Stevens,F/C,30.0,"6'6""",180 lbs,Connecticut,184.0,NaN,Chicago Sky
25,2.0,FORWARD,Maddy Westbeld,F,24.0,"6'3""",-,-,857.0,NaN,Chicago Sky
26,2.0,FORWARD,Elizabeth Williams,F/C,33.0,"6'3""",200 lbs,Duke,57.0,NaN,Chicago Sky
27,2.0,CENTER,Kamilla Cardoso,C,25.0,"6'7""",215 lbs,-,796.0,NaN,Chicago Sky
28,7.0,GUARD,Paige Bueckers,G,24.0,"6'0""",-,-,844.0,NaN,Dallas Wings
29,7.0,GUARD,Azzi Fudd,G,23.0,"5'11""",165 lbs,-,907.0,NaN,Dallas Wings
30,7.0,GUARD,Aziaha James,G,23.0,"5'10""",-,-,855.0,NaN,Dallas Wings
31,7.0,GUARD,Haley Jones,G/F,25.0,"6'1""",202 lbs,-,713.0,NaN,Dallas Wings
32,7.0,GUARD,Arike Ogunbowale,G,29.0,"5'8""",165 lbs,-,266.0,NaN,Dallas Wings
33,7.0,GUARD,Odyssey Sims,G,33.0,"5'8""",155 lbs,Baylor,149.0,NaN,Dallas Wings
34,7.0,GUARD,Sug Sutton,G,27.0,"5'8""",140 lbs,-,552.0,NaN,Dallas Wings
35,7.0,GUARD,Costanza Verona,G,26.0,"5'6""",-,-,905.0,NaN,Dallas Wings
36,7.0,FORWARD,Alysha Clark,F,38.0,"5'11""",167 lbs,Middle Tennessee State,89.0,NaN,Dallas Wings
37,7.0,FORWARD,Awak Kuier,F,24.0,"6'6""",168 lbs,-,602.0,NaN,Dallas Wings
38,7.0,FORWARD,Jessica Shepard,F,29.0,"6'4""",175 lbs,-,269.0,NaN,Dallas Wings
39,7.0,FORWARD,Maddy Siegrist,F,26.0,"6'2""",175 lbs,-,715.0,NaN,Dallas Wings
40,7.0,FORWARD,Alanna Smith,F,29.0,"6'4""",177 lbs,-,250.0,NaN,Dallas Wings
41,7.0,CENTER,Li Yueru,C,27.0,"6'7""",-,-,525.0,NaN,Dallas Wings
42,12.0,GUARD,Zia Cooke,G,25.0,"5'9""",163 lbs,-,726.0,NaN,Seattle Storm
43,12.0,GUARD,Natisha Hiedeman,G,29.0,"5'8""",132 lbs,-,239.0,NaN,Seattle Storm
44,12.0,GUARD,Flau'jae Johnson,G,22.0,"5'10""",170 lbs,-,917.0,NaN,Seattle Storm
45,12.0,GUARD,Taina Mair,G,22.0,"5'9""",-,-,927.0,NaN,Seattle Storm
46,12.0,GUARD,Jade Melbourne,G,23.0,"5'10""",145 lbs,-,640.0,NaN,Seattle Storm
47,12.0,GUARD,Katie Lou Samuelson,G,29.0,"6'3""",163 lbs,-,226.0,NaN,Seattle Storm
48,12.0,GUARD,Taylor Thierry,G/F,23.0,"6'1""",-,-,868.0,NaN,Seattle Storm
49,12.0,FORWARD,Mackenzie Holmes,F,25.0,"6'3""",185 lbs,-,738.0,NaN,Seattle Storm